build:
  image: ruby
  environment:
    - LANG=C.UTF-8
    - LC_ALL=C.UTF-8
  commands:
    - bundle install --deployment
    - bundle clean
    - bundle exec rake generate
cache:
  mount:
    - vendor/bundle
deploy:
  rsync:
    user: michael
    host: bedrock.miscjunk.net
    port: 22
    source: public/
    target: /srv/http/michael.limiero.com
    delete: true
    recursive: true
